module.exports = {
  Account: require('./Account'),
  User: require('./User'),
  Role: require('./Role'),
  Service: require('./Service'),
  Service_event: require('./Service-event'),
  Event: require('./Event'),
  Image: require('./Image'),
  Permission: require('./Permission'),
  Rate: require('./Rate'),
  RoleAccounts: require('./RoleAccounts'),
  RolePermissions: require('./RolePermissions'),
  Service: require('./Service'),
  ServiceEvents: require('./ServiceEvents'),
  User: require('./User'),
  Category: require('./Category'),
  Association: require('./Association'),
  Slugify: require('./Slugify'),
  Cart: require('./Cart'),
  Event: require('./Event'),
  Bill: require('./Bill'),
  BillDetail: require('./BillDetail'),
  Tag: require('./Tag'), 
  TagServices: require('./TagServices'),
};
