
GET http://localhost:4000

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "user123",
    "email": "user123@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "qhuy4919",
    "password": "12345678"
}
